name: time_trip
description: Your app description
publish_to: 'none' # Remove this if publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.9.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/instagram.png
    - assets/facebook.png
    - assets/google.png
    - assets/face_sample.png
